src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CarrierName;

    /**
     * @ORM\Column(type="float")
     */
    private $CarrierPrice;

    /**
     * @ORM\Column(type="text")
     */
    private $delivery;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetails::class, mappedBy="customerOrder")
     */
    private $orderDetails;

    /**
     * @ORM\Column(type="integer")
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stripeSessionId;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->CarrierName;
    }

    public function setCarrierName(string $CarrierName): self
    {
        $this->CarrierName = $CarrierName;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->CarrierPrice;
    }

    public function setCarrierPrice(float $CarrierPrice): self
    {
        $this->CarrierPrice = $CarrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetails>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetails $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setCustomerOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetails $orderDetail): self
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getCustomerOrder() === $this) {
                $orderDetail->setCustomerOrder(null);
            }
        }

        return $this;
    }

	public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getTotal()
    {
        $total = null;
        foreach ($this->getOrderDetails()->getValues() as $product) {
            $total += $product->getTotal();
        }

        return $total;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripeSessionId;
    }

    public function setStripeSessionId(?string $stripeSessionId): self
    {
        $this->stripeSessionId = $stripeSessionId;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Address;
use App\Entity\Carrier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        /** @var User $user */
        $user = $options['user'];

        $builder
            ->add('addresses', EntityType::class, [
                'class'        => Address::class,
                'choices'      => $user->getAddresses(),
                'label'        => false,
                'required'     => true,
                'multiple'     => false,
                'expanded'     => true
            ])
            ->add('carriers', EntityType::class, [
                'class'        => Carrier::class,
                'label'        => 'Choisissez un transporteur',
                'required'     => true,
                'multiple'     => false,
                'expanded'     => true
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Valider ma commande',
                'attr'  => [
                    'class' => 'btn btn-success btn-block'
                ]
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'user' => array()
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\OrderDetails;
use App\Form\OrderType;
use App\Util\Cart;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }


    /**
     * @Route("/commande", name="app_order")
     */
    public function index(Cart $cart): Response
    {
        if (!$this->getUser()->getAddresses()->getValues()) {
            return $this->redirectToRoute('app_account_address_add');
        }

        $form = $this->createForm(OrderType::class, null, [
            'user' => $this->getUser()
        ]);

        return $this->render('order/index.html.twig', [
            'form' => $form->createView(),
            'cart' => $cart->getDataOnCart()
        ]);
    }

    /**
     * @Route("/commande/recapitulatif", name="app_order_recap", methods={"POST"})
     */
    public function add(Request $request, Cart $cart): Response
    {
        $form = $this->createForm(OrderType::class, null, [
            'user' => $this->getUser()
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $date = new \DateTime();
            $carrier = $form->get('carriers')->getData();
            $delivery = $form->get('addresses')->getData();

            $deliveryContent = sprintf('%s %s', $delivery->getFirstname(), $delivery->getLastname());
            $deliveryContent .= sprintf('<br />%s', $delivery->getPhone());
            if ($delivery->getCompany()) $deliveryContent .= sprintf('<br />%s', $delivery->getCompany());
            $deliveryContent .= sprintf('<br />%s',$delivery->getAddress());
            $deliveryContent .= sprintf('<br />%s %s (%s)', $delivery->getPostal(), $delivery->getCity(), $delivery->getCountry());


            // enregistrement de la commande dans « Order »
            $order = (new Order())
                                ->setUser($this->getUser())
                                ->setCreatedAt($date)
                                ->setCarrierName($carrier->getName())
                                ->setCarrierPrice($carrier->getPrice())
                                ->setDelivery($deliveryContent)
                                ->setState(0) // 0 = paiement non effectué
                                ->setReference(sprintf('%s-%s', $date->format('dmY'), uniqid()))
            ;
            $this->entityManager->persist($order);

            // enregistrement des produits dans « OrderDetails »   
            foreach ($cart->getDataOnCart() as $product) {
                $orderDetails = (new OrderDetails())
                                                ->setCustomerOrder($order)
                                                ->setProduct($product['product']->getName())
                                                ->setQuantity($product['quantity'])
                                                ->setPrice($product['product']->getPrice())
                                                ->setTotal($product['product']->getPrice() * $product['quantity'])
                ;
                $this->entityManager->persist($orderDetails);
            }

            $this->entityManager->flush();

            return $this->render('order/add.html.twig', [
                'cart'      => $cart->getDataOnCart(),
                'carrier'   => $carrier,
                'delivery'  => $deliveryContent,
                'reference' => $order->getReference()
            ]);
        }

        return $this->redirectToRoute('app_cart');
    }
}

templates/order/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement de ma commande{% endblock %}

{% block javascripts %}
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{{ asset('assets/js/stripe-script.js') }}" defer></script>
{% endblock %}

{% block body %}
    <h1>Récapitulatif</h1>
    <p>Veuillez vérifiez vos informations avant de payer votre commande</p>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <strong>Adresse de livaison :</strong>
            <br>
            <div class="mt-4 form-check">
                {{ delivery|raw }}
            </div>
            <hr>
            <strong> Transporteur choisi :</strong>
            <br>
            <div class="form-check">
                {{ carrier.name }} : {{ (carrier.price / 100)|number_format(2, ',', '.') }} &euro;
                <br>
                {{ carrier.description }}
            </div>
            
        </div>
        <div class="col-md-6">
            <div class="text-center order-title">
                <b>Ma commande :</b>
            </div>
            <div class="order-summary">
                {% set total = null %}
                {% for key, p in cart %}
                    <div class="row{% if key > 0 %} mt-2{% endif %}">
                        <div class="col-2">
                            <img height="75px" src="{{ asset('uploads/images/')}}{{ p.product.illustration }}" alt="image {{ p.product.name }}">
                        </div>
                        <div class="col-8 my-auto text-center">
                            <b>{{ p.product.name }}</b>
                            <br>
                            <small>
                                {{ p.product.subtitle }}
                                <br>
                                x {{ p.quantity }}
                            </small>
                        </div>
                        <div class="col-2 my-auto">
                            {{ ((p.product.price * p.quantity) / 100)|number_format(2, ',', '.') }} &euro;
                        </div>
                    </div>
                    {% set total = total + (p.product.price * p.quantity) %}
                {% endfor %}
            </div>

            <hr>
            <strong>Sous-total : </strong>{{ (total / 100)|number_format(2, ',', '.') }} &euro;
            <br>
            <strong>Livraison : </strong>{{ (carrier.price / 100)|number_format(2, ',', '.') }} &euro;
            <hr>
            <strong>Total : </strong>{{ ((total / 100) + (carrier.price / 100))|number_format(2, ',', '.') }} &euro;
            <a class="mt-3 btn btn-success btn-block" id="checkout-button" data-reference-for-path="{{ reference }}">Payer | {{ ((total / 100) + (carrier.price / 100))|number_format(2, ',', '.') }} &euro;</a>
        </div>
    </div>
{% endblock %}

templates/order/fail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Erreur de paiement{% endblock %}

{% block body %}
    <h1>Erreur de paiement</h1>
    <p>Désolé <strong>{{ order.user.firstname }} {{ order.user.lastname }}</strong> ...</p>
    <p>
        Il semblerait que votre paiement ait échouée pour votre commande n°<strong>{{ order.reference }}</strong>
        <br>
        Une confirmation d'erreur vient de vous être envoyée par e-mail à l'adresse <strong>{{ order.user.email }}</strong>
        <hr>
    </p>
    <a class="btn btn-success" href="{{ path('app_order')}}">Réessayer le paiement</a>
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Valider ma commande{% endblock %}

{% block body %}
    <h1>Je passe ma commande</h1>
    <p>Choisissez vos préférences avant de passer votre commande sur la e-boutique</p>
    <hr>
    <div class="row">
        <div class="col-md-6 ">
            {% set formHtml %}
                {{ form_start(form, { action: path('app_order_recap') }) }}
                    {{ form_label(form.addresses, 'Choisissez votre adresse de livraison') }}
                    <div class="text-center">
                        <a href="{{ path('app_account_address_add') }}">Ajouter une nouvelle adresse</a>
                    </div>
                {{ form_end(form) }}
            {% endset %}
            {{ formHtml|replace({'[br]' : '<br>'})|raw }}
        </div>
        <div class="col-md-6">
            <div class="text-center order-title">
                <b>Récapitulation de la commande</b>
                <br>
                Retrouvez le récapitulatif de vos produits
            </div>
            <div class="order-summary">
                {% for key, p in cart %}
                    <div class="row{% if key > 0 %} mt-2{% endif %}">
                        <div class="col-2">
                            <img height="75px" src="{{ asset('uploads/images/')}}{{ p.product.illustration }}" alt="image {{ p.product.name }}">
                        </div>
                        <div class="col-8 my-auto text-center">
                            <b>{{ p.product.name }}</b>
                            <br>
                            <small>{{ p.product.subtitle }}</small>
                        </div>
                        <div class="col-2 my-auto">
                            x {{ p.quantity }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/order/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Confirmation de paiement de commande{% endblock %}

{% block body %}
    <h1>Confirmation de commande</h1>
    <p>Félicitations <strong>{{ order.user.firstname }} {{ order.user.lastname }}</strong> !</p>
    <p>
        Nous vous remercions pour votre commande n°<strong>{{ order.reference }}</strong>
        <br>
        Une confirmation vient de vous être envoyée par e-mail à l'adresse <strong>{{ order.user.email }}</strong>
        <hr>
        Votre commande sera livrée par <strong>{{ order.carrierName }}</strong> à l'adresse suivante :
        <br>
        {{ order.delivery|raw }}
        <hr>
        Pour suivre votre commande, rendez-vous dans votre <a href="{{ path('app_account_order')}}">compte</a>
    </p>
{% endblock %}